# Generated by Django 3.2.5 on 2021-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pImg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
