# Generated by Django 3.2.5 on 2021-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_alter_product_pimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_category',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=200, null=True),
        ),
    ]
