# Generated by Django 3.2.5 on 2021-08-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0008_auto_20210802_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
