# Generated by Django 3.2.5 on 2021-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0009_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
