# Generated by Django 3.2.5 on 2021-08-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0015_auto_20210804_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
