# Generated by Django 3.2.5 on 2021-08-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0017_alter_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
