# Generated by Django 3.2.5 on 2021-08-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0023_remove_product_digital'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupon_code',
            new_name='Coupon_code',
        ),
    ]
