# Generated by Django 3.2.5 on 2021-08-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0024_rename_cupon_code_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
