# Generated by Django 3.2.5 on 2021-08-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0025_orderitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='status',
            new_name='check_status',
        ),
    ]
